// const languages = {
//     "aa": "Afar",
//     "ab": "Abkhazian",
//     "ae": "Avestan",
//     "af": "Afrikaans",
//     "ak": "Akan",
//     "am": "Amharic",
//     "an": "Aragonese",
//     "ar": "Arabic",
//     "as": "Assamese",
//     "av": "Avaric",
//     "ay": "Aymara",
//     "az": "Azerbaijani",
//     "ba": "Bashkir",
//     "be": "Belarusian",
//     "bg": "Bulgarian",
//     "bh": "Bihari languages",
//     "bi": "Bislama",
//     "bm": "Bambara",
//     "bn": "Bengali",
//     "bo": "Tibetan",
//     "br": "Breton",
//     "bs": "Bosnian",
//     "ca": "Catalan",
//     "ce": "Chechen",
//     "ch": "Chamorro",
//     "co": "Corsican",
//     "cr": "Cree",
//     "cs": "Czech",
//     "cu": "Church Slavic",
//     "cv": "Chuvash",
//     "cy": "Welsh",
//     "da": "Danish",
//     "de": "German",
//     "dv": "Maldivian",
//     "dz": "Dzongkha",
//     "ee": "Ewe",
//     "el": "Greek",
//     "en": "English",
//     "eo": "Esperanto",
//     "es": "Spanish",
//     "et": "Estonian",
//     "eu": "Basque",
//     "fa": "Persian",
//     "ff": "Fulah",
//     "fi": "Finnish",
//     "fj": "Fijian",
//     "fo": "Faroese",
//     "fr": "French",
//     "fy": "Western Frisian",
//     "ga": "Irish",
//     "gd": "Gaelic",
//     "gl": "Galician",
//     "gn": "Guarani",
//     "gu": "Gujarati",
//     "gv": "Manx",
//     "ha": "Hausa",
//     "he": "Hebrew",
//     "hi": "Hindi",
//     "ho": "Hiri Motu",
//     "hr": "Croatian",
//     "ht": "Haitian",
//     "hu": "Hungarian",
//     "hy": "Armenian",
//     "hz": "Herero",
//     "ia": "Interlingua",
//     "id": "Indonesian",
//     "ie": "Interlingue",
//     "ig": "Igbo",
//     "ii": "Sichuan Yi",
//     "ik": "Inupiaq",
//     "io": "Ido",
//     "is": "Icelandic",
//     "it": "Italian",
//     "iu": "Inuktitut",
//     "ja": "Japanese",
//     "jv": "Javanese",
//     "ka": "Georgian",
//     "kg": "Kongo",
//     "ki": "Kikuyu",
//     "kj": "Kuanyama",
//     "kk": "Kazakh",
//     "kl": "Kalaallisut",
//     "km": "Central Khmer",
//     "kn": "Kannada",
//     "ko": "Korean",
//     "kr": "Kanuri",
//     "ks": "Kashmiri",
//     "ku": "Kurdish",
//     "kv": "Komi",
//     "kw": "Cornish",
//     "ky": "Kirghiz",
//     "la": "Latin",
//     "lb": "Luxembourgish",
//     "lg": "Ganda",
//     "li": "Limburgan",
//     "ln": "Lingala",
//     "lo": "Lao",
//     "lt": "Lithuanian",
//     "lu": "Luba-Katanga",
//     "lv": "Latvian",
//     "mg": "Malagasy",
//     "mh": "Marshallese",
//     "mi": "Maori",
//     "mk": "Macedonian",
//     "ml": "Malayalam",
//     "mn": "Mongolian",
//     "mr": "Marathi",
//     "ms": "Malay",
//     "mt": "Maltese",
//     "my": "Burmese",
//     "na": "Nauru",
//     "nb": "Norwegian",
//     "nd": "North Ndebele",
//     "ne": "Nepali",
//     "ng": "Ndonga",
//     "nl": "Dutch",
//     "nn": "Norwegian",
//     "no": "Norwegian",
//     "nr": "South Ndebele",
//     "nv": "Navajo",
//     "ny": "Chichewa",
//     "oc": "Occitan",
//     "oj": "Ojibwa",
//     "om": "Oromo",
//     "or": "Oriya",
//     "os": "Ossetic",
//     "pa": "Panjabi",
//     "pi": "Pali",
//     "pl": "Polish",
//     "ps": "Pushto",
//     "pt": "Portuguese",
//     "qu": "Quechua",
//     "rm": "Romansh",
//     "rn": "Rundi",
//     "ro": "Romanian",
//     "ru": "Russian",
//     "rw": "Kinyarwanda",
//     "sa": "Sanskrit",
//     "sc": "Sardinian",
//     "sd": "Sindhi",
//     "se": "Northern Sami",
//     "sg": "Sango",
//     "si": "Sinhala",
//     "sk": "Slovak",
//     "sl": "Slovenian",
//     "sm": "Samoan",
//     "sn": "Shona",
//     "so": "Somali",
//     "sq": "Albanian",
//     "sr": "Serbian",
//     "ss": "Swati",
//     "st": "Sotho, Southern",
//     "su": "Sundanese",
//     "sv": "Swedish",
//     "sw": "Swahili",
//     "ta": "Tamil",
//     "te": "Telugu",
//     "tg": "Tajik",
//     "th": "Thai",
//     "ti": "Tigrinya",
//     "tk": "Turkmen",
//     "tl": "Tagalog",
//     "tn": "Tswana",
//     "to": "Tonga",
//     "tr": "Turkish",
//     "ts": "Tsonga",
//     "tt": "Tatar",
//     "tw": "Twi",
//     "ty": "Tahitian",
//     "ug": "Uighur",
//     "uk": "Ukrainian",
//     "ur": "Urdu",
//     "uz": "Uzbek",
//     "ve": "Venda",
//     "vi": "Vietnamese",
//     "vo": "Volapük",
//     "wa": "Walloon",
//     "wo": "Wolof",
//     "xh": "Xhosa",
//     "yi": "Yiddish",
//     "yo": "Yoruba",
//     "za": "Zhuang",
//     "zh": "Chinese",
//     "zu": "Zulu"
// }

const languages = {
    "am-ET": "Amharic",
    "ar-SA": "Arabic",
    "be-BY": "Bielarus",
    "bem-ZM": "Bemba",
    "bi-VU": "Bislama",
    "bjs-BB": "Bajan",
    "bn-IN": "Bengali",
    "bo-CN": "Tibetan",
    "br-FR": "Breton",
    "bs-BA": "Bosnian",
    "ca-ES": "Catalan",
    "cop-EG": "Coptic",
    "cs-CZ": "Czech",
    "cy-GB": "Welsh",
    "da-DK": "Danish",
    "dz-BT": "Dzongkha",
    "de-DE": "German",
    "dv-MV": "Maldivian",
    "el-GR": "Greek",
    "en-GB": "English",
    "es-ES": "Spanish",
    "et-EE": "Estonian",
    "eu-ES": "Basque",
    "fa-IR": "Persian",
    "fi-FI": "Finnish",
    "fn-FNG": "Fanagalo",
    "fo-FO": "Faroese",
    "fr-FR": "French",
    "gl-ES": "Galician",
    "gu-IN": "Gujarati",
    "ha-NE": "Hausa",
    "he-IL": "Hebrew",
    "hi-IN": "Hindi",
    "hr-HR": "Croatian",
    "hu-HU": "Hungarian",
    "id-ID": "Indonesian",
    "is-IS": "Icelandic",
    "it-IT": "Italian",
    "ja-JP": "Japanese",
    "kk-KZ": "Kazakh",
    "km-KM": "Khmer",
    "kn-IN": "Kannada",
    "ko-KR": "Korean",
    "ku-TR": "Kurdish",
    "ky-KG": "Kyrgyz",
    "la-VA": "Latin",
    "lo-LA": "Lao",
    "lv-LV": "Latvian",
    "men-SL": "Mende",
    "mg-MG": "Malagasy",
    "mi-NZ": "Maori",
    "ms-MY": "Malay",
    "mt-MT": "Maltese",
    "my-MM": "Burmese",
    "ne-NP": "Nepali",
    "niu-NU": "Niuean",
    "nl-NL": "Dutch",
    "no-NO": "Norwegian",
    "ny-MW": "Nyanja",
    "ur-PK": "Pakistani",
    "pau-PW": "Palauan",
    "pa-IN": "Panjabi",
    "ps-PK": "Pashto",
    "pis-SB": "Pijin",
    "pl-PL": "Polish",
    "pt-PT": "Portuguese",
    "rn-BI": "Kirundi",
    "ro-RO": "Romanian",
    "ru-RU": "Russian",
    "sg-CF": "Sango",
    "si-LK": "Sinhala",
    "sk-SK": "Slovak",
    "sm-WS": "Samoan",
    "sn-ZW": "Shona",
    "so-SO": "Somali",
    "sq-AL": "Albanian",
    "sr-RS": "Serbian",
    "sv-SE": "Swedish",
    "sw-SZ": "Swahili",
    "ta-LK": "Tamil",
    "te-IN": "Telugu",
    "tet-TL": "Tetum",
    "tg-TJ": "Tajik",
    "th-TH": "Thai",
    "ti-TI": "Tigrinya",
    "tk-TM": "Turkmen",
    "tl-PH": "Tagalog",
    "tn-BW": "Tswana",
    "to-TO": "Tongan",
    "tr-TR": "Turkish",
    "uk-UA": "Ukrainian",
    "uz-UZ": "Uzbek",
    "vi-VN": "Vietnamese",
    "wo-SN": "Wolof",
    "xh-ZA": "Xhosa",
    "yi-YD": "Yiddish",
    "zu-ZA": "Zulu"
}